### ISSUE TITLE
> Task :app:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by phuongnvet-it** [tuanpmt/react-native-smartconfig#10]
`Nguyens-MacBook-Pro:SmartConfigAndroid nguyenphuong$ react-native run-android
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

> Configure project :app
WARNING: The specified Android SDK Build Tools version (28.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-smartconfig
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:compileDebugJavaWithJavac FAILED
/Volumes/Data/ReactNative/demo/SmartConfigAndroid/android/app/src/main/java/com/smartconfigandroid/MainApplication.java:5: error: cannot find symbol
import com.facebook.react.ReactApplication;
                         ^
  symbol:   class ReactApplication
  location: package com.facebook.react
/Volumes/Data/ReactNative/demo/SmartConfigAndroid/android/app/src/main/java/com/smartconfigandroid/MainApplication.java:6: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
                         ^
  symbol:   class ReactNativeHost
  location: package com.facebook.react
/Volumes/Data/ReactNative/demo/SmartConfigAndroid/android/app/src/main/java/com/smartconfigandroid/MainApplication.java:16: error: cannot find symbol
public class MainApplication extends Application implements ReactApplication {
                                                            ^
  symbol: class ReactApplication
/Volumes/Data/ReactNative/demo/SmartConfigAndroid/android/app/src/main/java/com/smartconfigandroid/MainApplication.java:18: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Volumes/Data/ReactNative/demo/SmartConfigAndroid/android/app/src/main/java/com/smartconfigandroid/MainApplication.java:39: error: cannot find symbol
  public ReactNativeHost getReactNativeHost() {
         ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Volumes/Data/ReactNative/demo/SmartConfigAndroid/android/app/src/main/java/com/smartconfigandroid/MainApplication.java:18: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                                                       ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Volumes/Data/ReactNative/demo/SmartConfigAndroid/android/app/src/main/java/com/smartconfigandroid/MainApplication.java:38: error: method does not override or implement a method from a supertype
  @Override
  ^
/Volumes/Data/ReactNative/demo/SmartConfigAndroid/android/app/src/main/java/com/smartconfigandroid/MainActivity.java:5: error: MainActivity is not abstract and does not override abstract method getPackages() in ReactActivity
public class MainActivity extends ReactActivity {
       ^
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
26 actionable tasks: 1 executed, 25 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:637:11)
    at Object.execFileSync (child_process.js:655:13)
    at runOnAllDevices (/Volumes/Data/ReactNative/demo/SmartConfigAndroid/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/Volumes/Data/ReactNative/demo/SmartConfigAndroid/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/Volumes/Data/ReactNative/demo/SmartConfigAndroid/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)`

**Comment by jomiva** [comment]
did you make it work?
